services:
    api:
        build: .
        restart: unless-stopped
        volumes:
            - /opt/amr-community/data:/data
        environment:
            PORT: "3000"
            DATA_DIR: /data
        networks:
            - coolify
        labels:
            - traefik.enable=true
            - traefik.http.routers.amr-community.rule=Host(`amr-api.weeb.ltd`)
            - traefik.http.routers.amr-community.entrypoints=https
            - traefik.http.routers.amr-community.tls=true
            - traefik.http.routers.amr-community.tls.certresolver=letsencrypt
            - traefik.http.services.amr-community.loadbalancer.server.port=3000

networks:
    coolify:
        external: true
